"use client";
import { PhoneProvider } from './context/PhoneContext';
import 'react-circular-progressbar/dist/styles.css';
import 'react-loading-skeleton/dist/skeleton.css'
import { Toaster } from "@/components/ui/toaster"
import NextTopLoader from 'nextjs-toploader';

import Footer from './components/Footer/Footer';
export const metadata = {
    title: 'RewindJobs',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body>
                <NextTopLoader
                    height={3}
                    speed={8}
                    showSpinner={false}
                />

                {children}
                <Toaster />
            </body>
        </html>
    )
}
